version: '3.8'
services:
  provider-service1:
    build: 
      context: ./provider-service
    ports:
      - "3103:3103"
      - "3105:3105"
      - "3102:3102"
      - "50617:50617"
    environment:
      - ANNOUNCE_MULTIADDR=/ip4/${IP_ADDRESS_SELF}/tcp/3105/http
      - LISTEN_MULTIADDR=/ip4/0.0.0.0/tcp/3105
      - PUBLISHER_KIND=libp2phttp
      - RETRIEVAL_MULTIADDR=/ip4/${IP_ADDRESS_SELF}/tcp/3103
      - DIRECT_ANNOUNCE_URL=https://cid.contact/ingest/announce
      - DELEGATED_ROUTING_MULTIADDR=/ip4/0.0.0.0/tcp/50617
      - DELEGATED_ROUTING_PROVIDER_ID=${DELEGATED_ROUTING_PROVIDER_ID1}
      - DELEGATED_ROUTING_CHUNK_SIZE=10000
      - DELEGATED_ROUTING_SNAPSHOT_SIZE=100000
      - DELEGATED_ROUTING_ADDRS=/ip4/${IP_ADDRESS_KUBO1}/tcp/4001
      - ADMIN_SERVER_MULTIADDR=/ip4/0.0.0.0/tcp/3102

  provider-service2:
    build: 
      context: ./provider-service
    ports:
      - "31032:3103"
      - "31052:3105"
      - "31022:3102"
      - "52617:50617"
    environment:
      - ANNOUNCE_MULTIADDR=/ip4/${IP_ADDRESS_SELF}/tcp/3105/http
      - LISTEN_MULTIADDR=/ip4/0.0.0.0/tcp/3105
      - PUBLISHER_KIND=libp2phttp
      - RETRIEVAL_MULTIADDR=/ip4/${IP_ADDRESS_SELF}/tcp/3103
      - DIRECT_ANNOUNCE_URL=https://cid.contact/ingest/announce
      - DELEGATED_ROUTING_MULTIADDR=/ip4/0.0.0.0/tcp/50617
      - DELEGATED_ROUTING_PROVIDER_ID=${DELEGATED_ROUTING_PROVIDER_ID2}
      - DELEGATED_ROUTING_CHUNK_SIZE=100
      - DELEGATED_ROUTING_SNAPSHOT_SIZE=1000
      - DELEGATED_ROUTING_ADDRS=/ip4/${IP_ADDRESS_KUBO2}/tcp/4001
      - ADMIN_SERVER_MULTIADDR=/ip4/0.0.0.0/tcp/3102

  ipfs-service:
    build:
      context: ./ipfs-service
      args:
        AWS_SECRET_KEY: ${AWS_SECRET_KEY1}
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY1}
        AWS_REGION: ${AWS_REGION1}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET1}
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

  ipns-service:
    build:
      context: ./ipns-service
      args:
        AWS_SECRET_KEY: ${AWS_SECRET_KEY2}
        AWS_ACCESS_KEY: ${AWS_ACCESS_KEY2}
        AWS_REGION: ${AWS_REGION2}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET2}
    ports:
      - "4002:4001"
      - "5002:5001"
      - "8081:8080"
