apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kubo-private-cors-plugin
  namespace: prod
plugin: cors
config:
  credentials: true
  methods:
    - GET
    - HEAD
    - PUT
    - PATCH
    - POST
    - DELETE
    - OPTIONS
  headers: 
    - Accept
    - Authorization
    - Content-Type
    - X-Requested-With
    - Origin
    - X-Deal-Parameter
    - Encryption
    - X-User-Key
  origins:
    - '*'
  max_age: null
  preflight_continue: false
  exposed_headers:
    - X-User-Key
