apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubo-private-ingress
  namespace: prod
  labels:
    app: kubo-private
  annotations:
    konghq.com/protocol: http
    konghq.com/strip-path: "true"
    konghq.com/plugins: "kubo-private-guard-plugin,"
spec:
  ingressClassName: kong
  rules:
    - host: upload.lighthouse.storage
      http:
        paths:
          - path: /ipfs
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubo-private-service
                port:
                  number: 5001