apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kubo-private-kubo-response-plugin
  namespace: prod
config:
  endpoint: "http://13.233.238.248:3000/validate-jwt"
  user_identifier : "X-User-Key"
  endpoint_validation_token : "Hello World"
plugin: kubo-response
