version: '3.8'
services:
  ipfs-public-node:
    container_name: ipfs-public-node
    build: 
      context: .
    environment:
      - AWS_SECRET_KEY={{ AWS_SECRET_KEY }}
      - AWS_ACCESS_KEY={{ AWS_ACCESS_KEY }}
      - AWS_REGION={{ AWS_REGION }}
      - AWS_S3_BUCKET={{ AWS_S3_BUCKET }}
      - ANNOUNCE_IP={{ ANNOUNCE_IP }}
    ports:
      - "14001:14001"
    volumes:
      - ipfs_data:/data/ipfs
    networks:
      - ipni_network

volumes:
  ipfs_data:

networks:
  ipni_network:
