stream {
    limit_conn_zone $binary_remote_addr zone=addr:10m;

    upstream ipfs_backend {
        server localhost:14001;
    }

    server {
        listen 4001;
        listen 4001 udp;
        proxy_pass ipfs_backend;

        # Limit connections per IP
        limit_conn addr 10;

        proxy_download_rate 500k;
        proxy_upload_rate 200k;

        # Set timeouts
        proxy_connect_timeout 60s;
    }
}
