apiVersion: v1
kind: ConfigMap
metadata:
  name: lighthouse-backend-config
  namespace: prod
data:
  DGN: "DEV"
  NODE_ENV: "development"
  AWS_REGION: "us-east-2"
  REDIS_URL: "redis://redis-service.prod.svc:6379"