apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lighthouse-backend-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lighthouse-backend-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
