FROM golang:1.22

LABEL maintainer "Ravish <ravish@lighthouse.storage>"

RUN git clone https://github.com/ipfs/go-ipfs && \
    cd go-ipfs && \
    go get github.com/lighthouse-web3/go-ds-s3/plugin@v0.14.0

# Add the plugin to the preload list.
RUN cd go-ipfs && \
    echo "\ns3ds github.com/lighthouse-web3/go-ds-s3/plugin 0" >> plugin/loader/preload_list &&\
    cat plugin/loader/preload_list && \
    cat plugin/loader/preload.go && \
    make build && \
    go mod tidy && \
    make build && \
    make install && \
    cp cmd/ipfs/ipfs /usr/local/bin/ipfs && \
    go install github.com/ipni/index-provider/cmd/provider@latest

# checkpoint --- echo ipfs version
RUN ipfs version
RUN  echo "IPFS VERSION IS -- $(ipfs version)"

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get install -y git curl jq

RUN node -v && npm -v
RUN npm i -g pm2 && pm2 install pm2-logrotate

COPY publisher/ /app/publisher/
RUN cd /app/publisher && ls && npm install

COPY setup.sh /setup.sh
RUN chmod +x /setup.sh

ENV IPFS_PATH=/data/ipfs \
    PROVIDER_PATH=/data/provider \
    API_PORT=5001 \
    GATEWAY_PORT=8080 \
    SWARM_PORT=4001

WORKDIR /data
ENTRYPOINT ["/setup.sh"]
