version: '3.8'
services:
  ipfs-ipni-service:
    container_name: ipfs-ipni-service
    build: .
    environment:
      - ANNOUNCE_MULTIADDR=/ip4/${IP_ADDRESS_SELF}/tcp/3105/http
      - LISTEN_MULTIADDR=/ip4/0.0.0.0/tcp/3105
      - PUBLISHER_KIND=libp2phttp
      - DIRECT_ANNOUNCE_URL=https://cid.contact/ingest/announce
      - DELEGATED_ROUTING_MULTIADDR=/ip4/0.0.0.0/tcp/50617
      - DELEGATED_ROUTING_ADDRS_TCP=/ip4/${IP_ADDRESS_SELF}/tcp/4001
      - DELEGATED_ROUTING_ADDRS_UDP=/ip4/${IP_ADDRESS_SELF}/udp/4001
      - AWS_SECRET_KEY={{ AWS_SECRET_KEY }}
      - AWS_ACCESS_KEY={{ AWS_ACCESS_KEY }}
      - AWS_REGION={{ AWS_REGION }}
      - AWS_S3_BUCKET={{ AWS_S3_BUCKET }}
      - ROUTE_ACCESS_TOKEN={{ ROUTE_ACCESS_TOKEN }}

    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
      - "3103:3103"
      - "3105:3105"
      - "3102:3102"
      - "50617:50617"
      - "8000:8000"
    volumes:
      - publisher:/app/publisher
      - ipfs_data:/data/ipfs
      - ipni_data:/root/.index-provider
volumes:
  ipfs_data:
  ipni_data:
  publisher:
