# Start from the official Go image
FROM golang:1.22.0

LABEL maintainer="Ravish <ravish@lighthouse.storage>"

RUN apt-get update && apt-get install -y git curl jq && \
    # Clone IPFS and install the S3 plugin
    git clone https://github.com/ipfs/kubo && \
    cd kubo && \
    go get github.com/lighthouse-web3/go-ds-s3/plugin@v0.14.0 && \
    echo "\ns3ds github.com/lighthouse-web3/go-ds-s3/plugin 0" >> plugin/loader/preload_list && \
    make build && \
    go mod tidy && \
    make build && \
    make install && \
    cp cmd/ipfs/ipfs /usr/local/bin/ipfs && \
    # Install the IPNI service
    go install github.com/ipni/index-provider/cmd/provider@v0.14.2

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs
RUN node -v && npm -v
RUN npm i -g pm2

COPY publisher/ /app/publisher/
RUN cd /app/publisher && ls && npm install

# Expose the port the Node.js app runs on
# EXPOSE 8000

CMD ["pm2", "start", "index.js"]

RUN ps aux
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENV IPFS_PATH=/data/ipfs \
    API_PORT=5001 \
    GATEWAY_PORT=8080 \
    SWARM_PORT=4001

# Expose necessary ports
# EXPOSE 4001 5001 8080 3103 3105 3102 50617

WORKDIR /data
ENTRYPOINT ["/entrypoint.sh"]
