deployment:
  test:
    enabled: false

controller:
  proxy:
    enabled: true
    nameOverride: "{{ .Release.Name }}-gateway-proxy"

    http:
      # Enable plaintext HTTP listen for the proxy
      enabled: false
      servicePort: 80
      containerPort: 8000
      # Set a nodePort which is available if service type is NodePort
      # nodePort: 32080
      # Additional listen parameters, e.g. "reuseport", "backlog=16384"
      parameters: []

    tls:
      # Enable HTTPS listen for the proxy
      enabled: true
      servicePort: 443
      containerPort: 8443
      # Set a target port for the TLS port in proxy service
      # overrideServiceTargetPort: 8000
      # Set a nodePort which is available if service type is NodePort
      # nodePort: 32443
      # Additional listen parameters, e.g. "reuseport", "backlog=16384"
      parameters:
      - http2

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

  podAnnotations:
    kuma.io/gateway: enabled
    # This port must match your Kong admin API port. 8444 is the default.
    # If you set gateway.admin.tls.containerPort, change these annotations
    # to use that value.
    traffic.kuma.io/exclude-outbound-ports: "8444"
    traffic.sidecar.istio.io/excludeOutboundPorts: "8444"

gateway:
  enabled: true
  deployment:
    kong:
      enabled: true

  plugins:
    configMaps:
    - name: kong-kubo-response-plugin-cm
      pluginName: kubo-response
    - name: kong-lighthouse-auth-plugin-cm
      pluginName: guard
      
  admin:
    enabled: true
    type: ClusterIP
    clusterIP: None

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"
    router_flavor: expressions
    log_level: debug
    upstream_keepalive_idle_timeout: 300
    upstream_keepalive_max_requests: 5000

      