gateway:
  plugins:
    configMaps:
    - name: kong-kubo-response-plugin-cm
      pluginName: kubo-response
    - name: kong-lighthouse-auth-plugin-cm
      pluginName: guard

env: 
  log_level : debug 